svn merge -r12201:12205 https://eris.llnl.gov/svn/slurm/branches/slurm-1.2

diff --git a/testsuite/expect/regression b/testsuite/expect/regression
--- a/testsuite/expect/regression
+++ b/testsuite/expect/regression
@@ -81,6 +81,10 @@ echo ""
 echo "Completions:$COMPLETIONS"
 echo "Failures:   $FAILURES"
 echo "Time (sec): $DELTA_TIME"
+
+echo "Completions:$COMPLETIONS" >& 2
+echo "Failures:   $FAILURES"    >& 2
+echo "Time (sec): $DELTA_TIME"  >& 2
 echo "Remember to check for mail send by tests" >& 2
 
 if [ $FAILURES -eq 0 ]
