Add description of failed test to stderr

diff --git a/testsuite/expect/regression b/testsuite/expect/regression
--- a/testsuite/expect/regression
+++ b/testsuite/expect/regression
@@ -62,7 +62,10 @@ for major in `seq 1 20`; do
 			COMPLETIONS=$((COMPLETIONS+1))
 		else
 			FAILURES=$((FAILURES+1))
-			echo "$TEST failed" >& 2
+			echo "=============" >& 2
+			echo "$TEST failed"  >& 2
+			grep "$TEST " README >& 2
+			echo "=============" >& 2
 		fi
 		/bin/echo "============================================"
 	done
