cgroup/v2 - Require dbus-1 version >= 1.11.16.
The cgroup/v2 plugin requires a version of dbus-1 >= 1.11.16 so that all
used symbols are available. This commit modifies the configure script so
that dbus-1 presence isn't just checked but also the required version is
satisfied. Otherwise, the plugin won't be built.

Some distributions like Amazon Linux 2 OS are shipped with:
- kernel-headers 5.10 (cgroup/v2 eBPF functionality requires >= 5.7)
- dbus-1 1.10.24 (cgroup/v2 dbus functionality requires >= 1.11.16)

So before this commit the configure script on such an example distribution
wouldn't emit any warning, but at build time the compiler would complain due
to missing symbols.

Bug 19615

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24888,19 +24888,19 @@ fi
 
 
 pkg_failed=no
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for dbus-1" >&5
-printf %s "checking for dbus-1... " >&6; }
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for dbus-1 >= 1.11.16" >&5
+printf %s "checking for dbus-1 >= 1.11.16... " >&6; }
 
 if test -n "$dbus_CFLAGS"; then
     pkg_cv_dbus_CFLAGS="$dbus_CFLAGS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"dbus-1\""; } >&5
-  ($PKG_CONFIG --exists --print-errors "dbus-1") 2>&5
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"dbus-1 >= 1.11.16\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "dbus-1 >= 1.11.16") 2>&5
   ac_status=$?
   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
   test $ac_status = 0; }; then
-  pkg_cv_dbus_CFLAGS=`$PKG_CONFIG --cflags "dbus-1" 2>/dev/null`
+  pkg_cv_dbus_CFLAGS=`$PKG_CONFIG --cflags "dbus-1 >= 1.11.16" 2>/dev/null`
 		      test "x$?" != "x0" && pkg_failed=yes
 else
   pkg_failed=yes
@@ -24912,12 +24912,12 @@ if test -n "$dbus_LIBS"; then
     pkg_cv_dbus_LIBS="$dbus_LIBS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"dbus-1\""; } >&5
-  ($PKG_CONFIG --exists --print-errors "dbus-1") 2>&5
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"dbus-1 >= 1.11.16\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "dbus-1 >= 1.11.16") 2>&5
   ac_status=$?
   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
   test $ac_status = 0; }; then
-  pkg_cv_dbus_LIBS=`$PKG_CONFIG --libs "dbus-1" 2>/dev/null`
+  pkg_cv_dbus_LIBS=`$PKG_CONFIG --libs "dbus-1 >= 1.11.16" 2>/dev/null`
 		      test "x$?" != "x0" && pkg_failed=yes
 else
   pkg_failed=yes
@@ -24938,9 +24938,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-                dbus_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "dbus-1" 2>&1`
+                dbus_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "dbus-1 >= 1.11.16" 2>&1`
         else
-                dbus_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "dbus-1" 2>&1`
+                dbus_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "dbus-1 >= 1.11.16" 2>&1`
         fi
         # Put the nasty error message in config.log where it belongs
         echo "$dbus_PKG_ERRORS" >&5
@@ -24966,8 +24966,8 @@ else
 fi
 
        if test "x$x_ac_have_dbus" = "xno"; then
-          { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: unable to link against dbus-1 libraries required for cgroup/v2" >&5
-printf "%s\n" "$as_me: WARNING: unable to link against dbus-1 libraries required for cgroup/v2" >&2;}
+          { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: unable to locate dbus-1 development headers >= 1.11.16" >&5
+printf "%s\n" "$as_me: WARNING: unable to locate dbus-1 development headers >= 1.11.16" >&2;}
        fi
 
 
