Clarify the warning message when BPF tokens are not supported
The previous warning message sounded like the cgroup/v2 plugin would not be
built, however only BPF token support is disabled if it is not found.

Changelog: Clarify warning when BPF tokens are not supported.
Ticket: 24352
Cherry-picked: 78fbfbeae9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27391,8 +27391,8 @@ rm -f core conftest.err conftest.$ac_objext conftest.beam \
 printf "%s\n" "#define HAVE_BPF_TOKENS 1" >>confdefs.h
 
       else
-        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: unable to link against a bpf.h from kernel-headers, version >= 6.9 required for cgroup/v2" >&5
-printf "%s\n" "$as_me: WARNING: unable to link against a bpf.h from kernel-headers, version >= 6.9 required for cgroup/v2" >&2;}
+        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: unable to build with BPF token support, BPF token support will be disabled. kernel-headers version >= 6.9 required to enable BPF token support ." >&5
+printf "%s\n" "$as_me: WARNING: unable to build with BPF token support, BPF token support will be disabled. kernel-headers version >= 6.9 required to enable BPF token support ." >&2;}
       fi
     fi
 
