ok it looks like we can really find perl now

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21704,8 +21704,8 @@ fi
 
 
 
-   { echo "$as_me:$LINENO: checking for PERL site dir" >&5
-echo $ECHO_N "checking for PERL site dir... $ECHO_C" >&6; }
+   { echo "$as_me:$LINENO: checking perl usability" >&5
+echo $ECHO_N "checking perl usability... $ECHO_C" >&6; }
 
    perl_dir=`perl -MConfig -e 'print $Config{archlib};'`
 
@@ -21718,10 +21718,62 @@ fi
 
 
    ac_perl='Not Found'
-   ac_have_perl_core="no"
    if test -d "$perl_dir/CORE" ; then
          ac_perl=$perl_dir
-	 ac_have_perl_core="yes"
+ 	 save_LIBS="$LIBS"
+   	 LIBS="$save_LIBS -L$perl_dir/CORE -lperl"
+ 	 save_CFLAGS="$CFLAGS"
+   	 CFLAGS="$save_CFLAGS -I$perl_dir/CORE"
+	 cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <EXTERN.h>
+	    	      #include <perl.h>
+int
+main ()
+{
+PerlInterpreter * interp; interp=perl_alloc();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_perl="Not Found"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+        LIBS="$save_LIBS"
+        CFLAGSS="$save_CFLAGS"
+        if test "$ac_perl" != "Not Found"; then
+            { echo "$as_me:$LINENO: result: PERL test program built properly." >&5
+echo "${ECHO_T}PERL test program built properly." >&6; }
 
 cat >>confdefs.h <<_ACEOF
 #define PERL_SITE_DIR "$perl_dir"
@@ -21732,11 +21784,14 @@ cat >>confdefs.h <<_ACEOF
 #define PERL_CORE_DIR "$perl_dir/CORE"
 _ACEOF
 
+	else
+            { echo "$as_me:$LINENO: WARNING: *** PERL test program execution failed." >&5
+echo "$as_me: WARNING: *** PERL test program execution failed." >&2;}
+        fi
+
+
    fi
 
-
-   { echo "$as_me:$LINENO: result: $ac_perl" >&5
-echo "${ECHO_T}$ac_perl" >&6; }
 
  if test "x$ac_perl" != "xNot Found"; then
   HAVE_PERL_CORE_DIR_TRUE=
