Disable machinefile with SLURM

diff --git a/mpich1/trunk/util/mpirun.args.in b/mpich1/trunk/util/mpirun.args.in
--- a/mpich1/trunk/util/mpirun.args.in
+++ b/mpich1/trunk/util/mpirun.args.in
@@ -263,6 +263,10 @@ while [ 1 -le $# ] ; do
 	shift
 	;;
     -machinefile)
+	if [ -n $SLURM_JOBID ] ; then
+           echo "error: machinefile incompatible with SLURM"
+           exit 1
+        fi
         machineFile="$1"
 	eval machineFile$narch="$1"
 	shift
