added ldflags for bgl systems and set the version of the mysql api to 5.0.0+

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -916,6 +916,7 @@ PTHREAD_CC
 PTHREAD_LIBS
 PTHREAD_CFLAGS
 BG_INCLUDES
+BG_LDFLAGS
 SEMAPHORE_SOURCES
 SEMAPHORE_LIBS
 NCURSES
@@ -7115,7 +7116,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7118 "configure"' > conftest.$ac_ext
+  echo '#line 7119 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9221,11 +9222,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9224: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9225: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9228: \$? = $ac_status" >&5
+   echo "$as_me:9229: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9511,11 +9512,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9514: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9515: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9518: \$? = $ac_status" >&5
+   echo "$as_me:9519: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9615,11 +9616,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9618: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9619: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9622: \$? = $ac_status" >&5
+   echo "$as_me:9623: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11992,7 +11993,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11995 "configure"
+#line 11996 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12092,7 +12093,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12095 "configure"
+#line 12096 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14493,11 +14494,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14496: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14497: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14500: \$? = $ac_status" >&5
+   echo "$as_me:14501: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14597,11 +14598,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14600: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14601: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14604: \$? = $ac_status" >&5
+   echo "$as_me:14605: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16195,11 +16196,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16198: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16199: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16202: \$? = $ac_status" >&5
+   echo "$as_me:16203: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16299,11 +16300,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16302: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16303: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16306: \$? = $ac_status" >&5
+   echo "$as_me:16307: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18519,11 +18520,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18522: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18523: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18526: \$? = $ac_status" >&5
+   echo "$as_me:18527: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18809,11 +18810,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18812: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18813: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18816: \$? = $ac_status" >&5
+   echo "$as_me:18817: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18913,11 +18914,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18916: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18917: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18920: \$? = $ac_status" >&5
+   echo "$as_me:18921: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -24774,6 +24775,7 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
 
   	if test ! -z "$have_bg_files" ; then
       		BG_INCLUDES="$bg_includes"
+		BG_LDFLAGS="-L$bg_dir/lib64"
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_BG_FILES 1
@@ -24807,6 +24809,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
    	fi
+
 
 
 
@@ -25364,18 +25367,31 @@ fi
         	{ echo "$as_me:$LINENO: WARNING: *** mysql_config not found. Evidently no MySQL install on system." >&5
 echo "$as_me: WARNING: *** mysql_config not found. Evidently no MySQL install on system." >&2;}
 	else
+		# check for mysql-5.0.0+
+		mysql_config_major_version=`$HAVEMYSQLCONFIG --version | \
+			sed 's/\([0-9]*\).\([0-9]*\).\([a-zA-Z0-9]*\)/\1/'`
+    		mysql_config_minor_version=`$HAVEMYSQLCONFIG --version | \
+			sed 's/\([0-9]*\).\([0-9]*\).\([a-zA-Z0-9]*\)/\2/'`
+    		mysql_config_micro_version=`$HAVEMYSQLCONFIG --version | \
+			sed 's/\([0-9]*\).\([0-9]*\).\([a-zA-Z0-9]*\)/\3/'`
+
+		if test $mysql_config_major_version -lt 5; then
+	   		{ echo "$as_me:$LINENO: WARNING: *** mysql-$mysql_config_major_version.$mysql_config_minor_version.$mysql_config_micro_version available, we need >= mysql-5.0.0 installed for the mysql interface." >&5
+echo "$as_me: WARNING: *** mysql-$mysql_config_major_version.$mysql_config_minor_version.$mysql_config_micro_version available, we need >= mysql-5.0.0 installed for the mysql interface." >&2;}
+            		ac_have_mysql="no"
+		else
 		# mysql_config puts -I on the front of the dir.  We don't
 		# want that so we remove it.
-		MYSQL_CFLAGS=`$HAVEMYSQLCONFIG --cflags`
-		MYSQL_LIBS=`$HAVEMYSQLCONFIG --libs_r`
-		if test -z "$MYSQL_LIBS"; then
-			MYSQL_LIBS=`$HAVEMYSQLCONFIG --libs`
-		fi
-		save_CFLAGS="$CFLAGS"
-		save_LIBS="$LIBS"
-       		CFLAGS="$MYSQL_CFLAGS $save_CFLAGS"
-		LIBS="$MYSQL_LIBS $save_LIBS"
-		cat >conftest.$ac_ext <<_ACEOF
+			MYSQL_CFLAGS=`$HAVEMYSQLCONFIG --cflags`
+			MYSQL_LIBS=`$HAVEMYSQLCONFIG --libs_r`
+			if test -z "$MYSQL_LIBS"; then
+				MYSQL_LIBS=`$HAVEMYSQLCONFIG --libs`
+			fi
+			save_CFLAGS="$CFLAGS"
+			save_LIBS="$LIBS"
+       			CFLAGS="$MYSQL_CFLAGS $save_CFLAGS"
+			LIBS="$MYSQL_LIBS $save_LIBS"
+			cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -25386,12 +25402,12 @@ int
 main ()
 {
 
-          		int main()
-          		{
-				MYSQL mysql;
-            			(void) mysql_init(&mysql);
-				(void) mysql_close(&mysql);
-            		}
+          				int main()
+          				{
+						MYSQL mysql;
+            					(void) mysql_init(&mysql);
+						(void) mysql_close(&mysql);
+            				}
 
   ;
   return 0;
@@ -25425,10 +25441,10 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
-		CFLAGS="$save_CFLAGS"
-		LIBS="$save_LIBS"
-       		if test "$ac_have_mysql" == "yes"; then
-            		{ echo "$as_me:$LINENO: result: MySQL test program built properly." >&5
+			CFLAGS="$save_CFLAGS"
+			LIBS="$save_LIBS"
+       			if test "$ac_have_mysql" == "yes"; then
+            			{ echo "$as_me:$LINENO: result: MySQL test program built properly." >&5
 echo "${ECHO_T}MySQL test program built properly." >&6; }
 
 
@@ -25437,11 +25453,12 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_MYSQL 1
 _ACEOF
 
-	        else
- 			MYSQL_CFLAGS=""
-			MYSQL_LIBS=""
-       			{ echo "$as_me:$LINENO: WARNING: *** MySQL test program execution failed." >&5
+			else
+ 				MYSQL_CFLAGS=""
+				MYSQL_LIBS=""
+       				{ echo "$as_me:$LINENO: WARNING: *** MySQL test program execution failed." >&5
 echo "$as_me: WARNING: *** MySQL test program execution failed." >&2;}
+			fi
 		fi
       	fi
 
@@ -28015,6 +28032,7 @@ PTHREAD_CC!$PTHREAD_CC$ac_delim
 PTHREAD_LIBS!$PTHREAD_LIBS$ac_delim
 PTHREAD_CFLAGS!$PTHREAD_CFLAGS$ac_delim
 BG_INCLUDES!$BG_INCLUDES$ac_delim
+BG_LDFLAGS!$BG_LDFLAGS$ac_delim
 SEMAPHORE_SOURCES!$SEMAPHORE_SOURCES$ac_delim
 SEMAPHORE_LIBS!$SEMAPHORE_LIBS$ac_delim
 NCURSES!$NCURSES$ac_delim
@@ -28059,7 +28077,6 @@ MUNGE_CPPFLAGS!$MUNGE_CPPFLAGS$ac_delim
 MUNGE_LDFLAGS!$MUNGE_LDFLAGS$ac_delim
 WITH_MUNGE_TRUE!$WITH_MUNGE_TRUE$ac_delim
 WITH_MUNGE_FALSE!$WITH_MUNGE_FALSE$ac_delim
-AUTHD_LIBS!$AUTHD_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -28101,6 +28118,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+AUTHD_LIBS!$AUTHD_LIBS$ac_delim
 AUTHD_CFLAGS!$AUTHD_CFLAGS$ac_delim
 WITH_AUTHD_TRUE!$WITH_AUTHD_TRUE$ac_delim
 WITH_AUTHD_FALSE!$WITH_AUTHD_FALSE$ac_delim
@@ -28108,7 +28126,7 @@ UTIL_LIBS!$UTIL_LIBS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 5; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 6; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
