Move the logic to test for configure --enable-load-env-no-login from configure.ac  into a separate auxdir/*m4 script

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1577,6 +1577,9 @@ Optional Features:
   --enable-pam            enable PAM (Pluggable Authentication Modules)
                           support
   --disable-iso8601       disable ISO 8601 time format support
+  --enable-load-env-no-login
+                          enable --get-user-env option to load user
+                          environment without .login
   --enable-bluegene-emulation
                           deprecated use --enable-bgl-emulation
   --enable-bgl-emulation  Run SLURM in BGL mode on a non-bluegene system
@@ -1585,9 +1588,6 @@ Optional Features:
   --enable-memory-leak-debug
                           enable memory leak debugging code for development
   --enable-front-end      enable slurmd operation on a front-end
-  --enable-load-env-no-login
-                          enable --get-user-env option to load user
-                          environment without login
   --enable-multiple-slurmd
                           enable multiple-slurmd support
 
@@ -23030,6 +23030,41 @@ echo "${ECHO_T}no" >&6; }
 
 
 
+  { echo "$as_me:$LINENO: checking whether sbatch --get-user-env option should load .login" >&5
+echo $ECHO_N "checking whether sbatch --get-user-env option should load .login... $ECHO_C" >&6; }
+  # Check whether --enable-load-env-no-login was given.
+if test "${enable_load_env_no_login+set}" = set; then
+  enableval=$enable_load_env_no_login;  case "$enableval" in
+        yes) x_ac_load_env_no_login=yes ;;
+         no) x_ac_load_env_no_login=no ;;
+          *) { echo "$as_me:$LINENO: result: doh!" >&5
+echo "${ECHO_T}doh!" >&6; }
+             { { echo "$as_me:$LINENO: error: bad value \"$enableval\" for --enable-load-env-no-login" >&5
+echo "$as_me: error: bad value \"$enableval\" for --enable-load-env-no-login" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      esac
+
+else
+  x_ac_load_env_no_login=no
+
+fi
+
+
+  if test "$x_ac_load_env_no_login" = yes; then
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define LOAD_ENV_NO_LOGIN 1
+_ACEOF
+
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+  fi
+
+
+
   { echo "$as_me:$LINENO: checking whether byte ordering is bigendian" >&5
 echo $ECHO_N "checking whether byte ordering is bigendian... $ECHO_C" >&6; }
 if test "${ac_cv_c_bigendian+set}" = set; then
@@ -27279,36 +27314,6 @@ else
 fi
 
 
-
-{ echo "$as_me:$LINENO: checking if user env vars should be based upon login" >&5
-echo $ECHO_N "checking if user env vars should be based upon login... $ECHO_C" >&6; }
-# Check whether --enable-load-env-no-login was given.
-if test "${enable_load_env_no_login+set}" = set; then
-  enableval=$enable_load_env_no_login;  case "$enableval" in
-     yes) x_ac_load_env_no_login=yes ;;
-      no) x_ac_load_env_no_login=no ;;
-       *) { echo "$as_me:$LINENO: result: doh!" >&5
-echo "${ECHO_T}doh!" >&6; }
-          { { echo "$as_me:$LINENO: error: bad value \"$enableval\" for --enable-load-env-no-login" >&5
-echo "$as_me: error: bad value \"$enableval\" for --enable-load-env-no-login" >&2;}
-   { (exit 1); exit 1; }; } ;;
-   esac
-
-
-fi
-
-if test "$x_ac_load_env_no_login" = yes; then
-
-cat >>confdefs.h <<\_ACEOF
-#define LOAD_ENV_NO_LOGIN 1
-_ACEOF
-
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
 
 { echo "$as_me:$LINENO: checking whether to enable multiple-slurmd support" >&5
 echo $ECHO_N "checking whether to enable multiple-slurmd support... $ECHO_C" >&6; }
