svn merge -r8418:8424 https://eris/svn/slurm/branches/slurm-1.1

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1054,6 +1054,8 @@ Optional Packages:
   --with-tags[=TAGS]
                           include additional configurations [automatic]
   --with-db2-dir=PATH     Specify path to DB2 library's parent directory
+  --with-bg-link=dynamic|static
+                          set brigdeapi linking type
   --with-bg-serial=NAME   set BG_SERIAL value BGL
   --with-xcpu=PATH        specify path to XCPU directory
   --with-slurmctld-port=N set slurmctld default port 6817
@@ -5657,7 +5659,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5660 "configure"' > conftest.$ac_ext
+  echo '#line 5662 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6765,7 +6767,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6768:" \
+echo "$as_me:6770:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7815,11 +7817,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7818: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7820: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7822: \$? = $ac_status" >&5
+   echo "$as_me:7824: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -8058,11 +8060,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8061: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8063: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8065: \$? = $ac_status" >&5
+   echo "$as_me:8067: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -8118,11 +8120,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8121: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8123: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8125: \$? = $ac_status" >&5
+   echo "$as_me:8127: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10303,7 +10305,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10306 "configure"
+#line 10308 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10401,7 +10403,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10404 "configure"
+#line 10406 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12590,11 +12592,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12593: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12595: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12597: \$? = $ac_status" >&5
+   echo "$as_me:12599: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12650,11 +12652,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12653: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12655: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12657: \$? = $ac_status" >&5
+   echo "$as_me:12659: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14011,7 +14013,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14014 "configure"
+#line 14016 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14109,7 +14111,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14112 "configure"
+#line 14114 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14946,11 +14948,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14949: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14951: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14953: \$? = $ac_status" >&5
+   echo "$as_me:14955: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15006,11 +15008,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15009: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15011: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15013: \$? = $ac_status" >&5
+   echo "$as_me:15015: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17041,11 +17043,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17044: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17046: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17048: \$? = $ac_status" >&5
+   echo "$as_me:17050: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17284,11 +17286,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17287: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17289: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17291: \$? = $ac_status" >&5
+   echo "$as_me:17293: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17344,11 +17346,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17347: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17349: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17351: \$? = $ac_status" >&5
+   echo "$as_me:17353: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19529,7 +19531,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19532 "configure"
+#line 19534 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19627,7 +19629,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19630 "configure"
+#line 19632 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21410,7 +21412,6 @@ done
 
 
 
-drn
 
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -23684,48 +23685,38 @@ LIBS="$PTHREAD_LIBS $LIBS"
 if test "${with_db2+set}" = set; then
   withval="$with_db2"
    trydb2dir=$withval
-
 fi;
 
-   bg_default_dirs="/bgl/BlueLight/ppcfloor/bglsys /opt/IBM/db2/V8.1 /u/bgdb2cli/sqllib /home/bgdb2cli/sqllib"
+   	bg_default_dirs="/bgl/BlueLight/ppcfloor/bglsys /opt/IBM/db2/V8.1 /u/bgdb2cli/sqllib /home/bgdb2cli/sqllib"
 
-   for bg_dir in $trydb2dir "" $bg_default_dirs; do
-      # Skip directories that don't exist
-      if test ! -z "$bg_dir" -a ! -d "$bg_dir" ; then
-         continue;
-      fi
+   	for bg_dir in $trydb2dir "" $bg_default_dirs; do
+      	# Skip directories that don't exist
+      		if test ! -z "$bg_dir" -a ! -d "$bg_dir" ; then
+         		continue;
+      		fi
 
-      # Search for required BG API libraries in the directory
-      if test -z "$have_bg_ar" -a -f "$bg_dir/lib/bglbootload.a" -a -f "$bg_dir/lib/bglsp440supt.a" ; then
-         if test ! -f "$bg_dir/lib64/libbglbridge_s.a" ; then
-            # Establish a link as required. Libtool requires the "lib" prefix
-            # to function properly. See
-            # "How to use --whole-archive arg with libtool"
-            # http://www.mail-archive.com/libtool@gnu.org/msg02792.html
-            { { echo "$as_me:$LINENO: error: $bg_dir/lib64/libbglbridge_s.a is required and does not exist" >&5
-echo "$as_me: error: $bg_dir/lib64/libbglbridge_s.a is required and does not exist" >&2;}
-   { (exit 1); exit 1; }; }
-         fi
+      		# Search for required BG API libraries in the directory
+      		if test -z "$have_bg_ar" -a -f "$bg_dir/lib64/libbglbridge.so" ; then
+         		have_bg_ar=yes
+       	 		bg_ldflags_d="$bg_ldflags_d -L$bg_dir/lib64 -L/usr/lib64 -lbglbridge -lbgldb -ltableapi -lbglmachine -lexpat -lsaymessage"
+	 		bg_ldflags_s="$bg_ldflags_s -Wl,-rpath $bg_dir/lib64 -Wl,-L$bg_dir/lib64 -Wl,-whole-archive -Wl,-lbglbridge_s -Wl,-no-whole-archive -lsaymessage_s -lbgldb_s -lbglmachine_s -ltableapi_s -L/usr/lib64 -lexpat"
+      		fi
 
-         have_bg_ar=yes
-         bg_ldflags="$bg_ldflags -Wl,-rpath $bg_dir/lib64 -Wl,-L$bg_dir/lib64 -Wl,-whole-archive -Wl,-lbglbridge_s -Wl,-no-whole-archive $bg_dir/lib/bglbootload.a $bg_dir/lib/bglsp440supt.a -lsaymessage_s -lbgldb_s -lbglmachine_s -ltableapi_s -L/usr/lib64 -lexpat"
+      		# Search for required DB2 library in the directory
+      		if test -z "$have_db2" -a -f "$bg_dir/lib64/libdb2.so" ; then
+         		have_db2=yes
+	 		bg_ldflags_d="$bg_ldflags_d -L$bg_dir/lib64 -ldb2"
+	 		bg_ldflags_s="$bg_ldflags_s -Wl,-rpath $bg_dir/lib64 -L$bg_dir/lib64 -ldb2"
+      		fi
 
-      fi
+      		# Search for headers in the directory
+      		if test -z "$have_bg_hdr" -a -f "$bg_dir/include/rm_api.h" ; then
+         		have_bg_hdr=yes
+         		bg_includes="-I$bg_dir/include"
+      		fi
+   	done
 
-      # Search for required DB2 library in the directory
-      if test -z "$have_db2" -a -f "$bg_dir/lib64/libdb2.so" ; then
-         have_db2=yes
-         bg_ldflags="$bg_ldflags -Wl,-rpath $bg_dir/lib64 -L$bg_dir/lib64 -ldb2"
-      fi
-
-      # Search for headers in the directory
-      if test -z "$have_bg_hdr" -a -f "$bg_dir/include/rm_api.h" ; then
-         have_bg_hdr=yes
-         bg_includes="-I$bg_dir/include"
-      fi
-   done
-
-   if test ! -z "$have_bg_ar" -a ! -z "$have_bg_hdr" -a ! -z "$have_db2" ; then
+   	if test ! -z "$have_bg_ar" -a ! -z "$have_bg_hdr" -a ! -z "$have_db2" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_BG 1
@@ -23736,11 +23727,72 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_FRONT_END 1
 _ACEOF
 
-      ac_with_readline="no"
+      		ac_with_readline="no"
 
-      saved_LDFLAGS="$LDFLAGS"
-      LDFLAGS="$saved_LDFLAGS $bg_ldflags"
-      cat >conftest.$ac_ext <<_ACEOF
+
+# Check whether --with-bg-link or --without-bg-link was given.
+if test "${with_bg_link+set}" = set; then
+  withval="$with_bg_link"
+  bg_link="$withval"
+fi;
+
+      		saved_LDFLAGS="$LDFLAGS"
+      	 	if test "$bg_link" = "dynamic"; then
+			LDFLAGS="$saved_LDFLAGS $bg_ldflags_d"
+         		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ int rm_set_serial(char *);
+int
+main ()
+{
+ rm_set_serial("");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_bg_files=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+{ { echo "$as_me:$LINENO: error: There is a problem dynamically linking to the bluegene api." >&5
+echo "$as_me: error: There is a problem dynamically linking to the bluegene api." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+			{ echo "$as_me:$LINENO: Bluegene bridgeapi dynamically linked" >&5
+echo "$as_me: Bluegene bridgeapi dynamically linked" >&6;}
+	 		bg_ldflags="$bg_ldflags_d"
+     		elif test "$bg_link" = "static"; then
+			LDFLAGS="$saved_LDFLAGS $bg_ldflags_s"
+         		cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -23788,35 +23840,144 @@ echo "$as_me: error: There is a problem linking to the bluegene api." >&2;}
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-      LDFLAGS="$saved_LDFLAGS"
-   fi
-   if test ! -z "$have_bg_files" ; then
-      BG_INCLUDES="$bg_includes"
-      BG_LDFLAGS="$bg_ldflags"
+         		{ echo "$as_me:$LINENO: Bluegene bridgeapi statically linked" >&5
+echo "$as_me: Bluegene bridgeapi statically linked" >&6;}
+	 		bg_ldflags="$bg_ldflags_s"
+      		else
+	 		LDFLAGS="$saved_LDFLAGS $bg_ldflags_d"
+         		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ int rm_set_serial(char *);
+int
+main ()
+{
+ rm_set_serial("");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_bg_files=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+      	 		if test -z "$have_bg_files" ; then
+         			LDFLAGS="$saved_LDFLAGS $bg_ldflags_s"
+         			cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ int rm_set_serial(char *);
+int
+main ()
+{
+ rm_set_serial("");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_bg_files=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+{ { echo "$as_me:$LINENO: error: There is a problem linking to the bluegene api." >&5
+echo "$as_me: error: There is a problem linking to the bluegene api." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+         			{ echo "$as_me:$LINENO: Bluegene bridgeapi statically linked" >&5
+echo "$as_me: Bluegene bridgeapi statically linked" >&6;}
+	 			bg_ldflags="$bg_ldflags_s"
+      			else
+ 	 			{ echo "$as_me:$LINENO: Bluegene bridgeapi dynamically linked" >&5
+echo "$as_me: Bluegene bridgeapi dynamically linked" >&6;}
+	 			bg_ldflags="$bg_ldflags_d"
+      			fi
+		fi
+      		LDFLAGS="$saved_LDFLAGS"
+   	fi
+  	if test ! -z "$have_bg_files" ; then
+      		BG_INCLUDES="$bg_includes"
+      		BG_LDFLAGS="$bg_ldflags"
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_BG_FILES 1
 _ACEOF
 
 
-      echo "$as_me:$LINENO: checking for BG serial value" >&5
+      		echo "$as_me:$LINENO: checking for BG serial value" >&5
 echo $ECHO_N "checking for BG serial value... $ECHO_C" >&6
-      bg_serial="BGL"
+      		bg_serial="BGL"
 
 # Check whether --with-bg-serial or --without-bg-serial was given.
 if test "${with_bg_serial+set}" = set; then
   withval="$with_bg_serial"
   bg_serial="$withval"
-
 fi;
-     echo "$as_me:$LINENO: result: $bg_serial" >&5
+     		echo "$as_me:$LINENO: result: $bg_serial" >&5
 echo "${ECHO_T}$bg_serial" >&6
 
 cat >>confdefs.h <<_ACEOF
 #define BG_SERIAL "$bg_serial"
 _ACEOF
 
-   fi
+   	fi
 
 
 
