ok the configure works correctly now

diff --git a/branches/slurm-1.3/configure b/branches/slurm-1.3/configure
--- a/branches/slurm-1.3/configure
+++ b/branches/slurm-1.3/configure
@@ -1574,7 +1574,9 @@ Optional Features:
   --enable-pam            enable PAM (Pluggable Authentication Modules)
                           support
   --enable-bluegene-emulation
-                          Run SLURM in bluegene mode on a non-bluegene system
+                          deprecated use --enable-bgl-emulation
+  --enable-bgl-emulation  Run SLURM in BGL mode on a non-bluegene system
+  --enable-bgp-emulation  Run SLURM in BG/P mode on a non-bluegene system
   --enable-debug          enable debugging code for development
   --enable-memory-leak-debug
                           enable memory leak debugging code for development
@@ -1593,9 +1595,9 @@ Optional Packages:
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
   --with-tags[=TAGS]      include additional configurations [automatic]
-  --with-db2-dir=PATH     Specify path to DB2 library's parent directory
-  --with-bg-serial=NAME   set BG_SERIAL value BGL
-  --with-bg-serial=NAME   set BG_SERIAL value BGP
+  --with-db2-dir=PATH     Specify path to DB2 librarys parent directory
+  --with-bg-serial=NAME   set BG_SERIAL value
+
   --with-xcpu=PATH        specify path to XCPU directory
   --with-pkg-config=PATH  Specify path to pkg-config binary
   --with-mysql_config=PATH
@@ -7122,7 +7124,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7125 "configure"' > conftest.$ac_ext
+  echo '#line 7127 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9228,11 +9230,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9231: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9233: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9235: \$? = $ac_status" >&5
+   echo "$as_me:9237: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9518,11 +9520,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9521: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9523: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9525: \$? = $ac_status" >&5
+   echo "$as_me:9527: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9622,11 +9624,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9625: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9627: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9629: \$? = $ac_status" >&5
+   echo "$as_me:9631: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11999,7 +12001,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12002 "configure"
+#line 12004 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12099,7 +12101,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12102 "configure"
+#line 12104 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14500,11 +14502,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14503: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14505: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14507: \$? = $ac_status" >&5
+   echo "$as_me:14509: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14604,11 +14606,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14607: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14609: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14611: \$? = $ac_status" >&5
+   echo "$as_me:14613: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16202,11 +16204,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16205: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16207: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16209: \$? = $ac_status" >&5
+   echo "$as_me:16211: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16306,11 +16308,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16309: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16311: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16313: \$? = $ac_status" >&5
+   echo "$as_me:16315: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18526,11 +18528,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18529: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18531: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18533: \$? = $ac_status" >&5
+   echo "$as_me:18535: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18816,11 +18818,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18819: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18821: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18823: \$? = $ac_status" >&5
+   echo "$as_me:18825: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18920,11 +18922,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18923: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18927: \$? = $ac_status" >&5
+   echo "$as_me:18929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -24658,7 +24660,8 @@ fi
 
 
 	# test for bluegene emulation mode
-   	# Check whether --enable-bluegene-emulation was given.
+
+  	# Check whether --enable-bluegene-emulation was given.
 if test "${enable_bluegene_emulation+set}" = set; then
   enableval=$enable_bluegene_emulation;  case "$enableval" in
 	  yes) bluegene_emulation=yes ;;
@@ -24670,7 +24673,19 @@ echo "$as_me: error: bad value \"$enableval\" for --enable-bluegene-emulation" >
 fi
 
 
-	if test "x$bluegene_emulation" = "xyes"; then
+  	# Check whether --enable-bgl-emulation was given.
+if test "${enable_bgl_emulation+set}" = set; then
+  enableval=$enable_bgl_emulation;  case "$enableval" in
+	  yes) bgl_emulation=yes ;;
+	  no)  bgl_emulation=no ;;
+	  *)   { { echo "$as_me:$LINENO: error: bad value \"$enableval\" for --enable-bgl-emulation" >&5
+echo "$as_me: error: bad value \"$enableval\" for --enable-bgl-emulation" >&2;}
+   { (exit 1); exit 1; }; }  ;;
+    	esac
+fi
+
+
+	if test "x$bluegene_emulation" = "xyes" -o "x$bgl_emulation" = "xyes"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_BG 1
@@ -24678,12 +24693,19 @@ _ACEOF
 
 
 cat >>confdefs.h <<\_ACEOF
+#define HAVE_BGL 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
 #define HAVE_FRONT_END 1
 _ACEOF
 
-    		{ echo "$as_me:$LINENO: Running in bluegene emulation mode" >&5
-echo "$as_me: Running in bluegene emulation mode" >&6;}
+    		{ echo "$as_me:$LINENO: Running in BG/L emulation mode" >&5
+echo "$as_me: Running in BG/L emulation mode" >&6;}
 		bg_default_dirs=""
+ 		#define bluegene_loaded so we don't load another bluegene conf
+		bluegene_loaded=yes
 	else
   	   	bg_default_dirs="/bgl/BlueLight/ppcfloor/bglsys /opt/IBM/db2/V8.1 /u/bgdb2cli/sqllib /home/bgdb2cli/sqllib"
 	fi
@@ -24716,16 +24738,6 @@ echo "$as_me: Running in bluegene emulation mode" >&6;}
    	done
 
    	if test ! -z "$have_bg_ar" -a ! -z "$have_bg_hdr" -a ! -z "$have_db2" ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_BG 1
-_ACEOF
-
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_FRONT_END 1
-_ACEOF
-
       		# ac_with_readline="no"
 		# Test to make sure the api is good
                 have_bg_files=yes
@@ -24783,6 +24795,21 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       		BG_INCLUDES="$bg_includes"
 
 cat >>confdefs.h <<\_ACEOF
+#define HAVE_BG 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BGL 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FRONT_END 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
 #define HAVE_BG_FILES 1
 _ACEOF
 
@@ -24813,14 +24840,50 @@ cat >>confdefs.h <<_ACEOF
 #define BG_SERIAL "$bg_serial"
 _ACEOF
 
-   	fi
+ 		#define bluegene_loaded so we don't load another bluegene conf
+		bluegene_loaded=yes
+  	fi
 
 
+
+
+	# test for bluegene emulation mode
+   	# Check whether --enable-bgp-emulation was given.
+if test "${enable_bgp_emulation+set}" = set; then
+  enableval=$enable_bgp_emulation;  case "$enableval" in
+	  yes) bgp_emulation=yes ;;
+	  no)  bgp_emulation=no ;;
+	  *)   { { echo "$as_me:$LINENO: error: bad value \"$enableval\" for --enable-bgp-emulation" >&5
+echo "$as_me: error: bad value \"$enableval\" for --enable-bgp-emulation" >&2;}
+   { (exit 1); exit 1; }; }  ;;
+    	esac
+fi
 
 
 	# Skip if already set
-   	if test ! -z "$have_bg_files" ; then
+   	if test "x$bluegene_loaded" = "xyes" ; then
 		bg_default_dirs=""
+	elif test "x$bgp_emulation" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BG 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BGP 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FRONT_END 1
+_ACEOF
+
+    		{ echo "$as_me:$LINENO: Running in BG/P emulation mode" >&5
+echo "$as_me: Running in BG/P emulation mode" >&6;}
+		bg_default_dirs=""
+ 		#define bluegene_loaded so we don't load another bluegene conf
+		bluegene_loaded=yes
 	else
 		bg_default_dirs="/bgsys/drivers/ppcfloor"
 	fi
@@ -24848,16 +24911,6 @@ _ACEOF
    	done
 
    	if test ! -z "$have_bgp_ar" -a ! -z "$have_bgp_hdr" ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_BG 1
-_ACEOF
-
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_FRONT_END 1
-_ACEOF
-
       		# ac_with_readline="no"
 		# Test to make sure the api is good
                 saved_LDFLAGS="$LDFLAGS"
@@ -24914,14 +24967,23 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       		BG_INCLUDES="$bg_includes"
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_BG_FILES 1
+#define HAVE_BG 1
 _ACEOF
 
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_BGP_FILES 1
+#define HAVE_BGP 1
 _ACEOF
 
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FRONT_END 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BG_FILES 1
+_ACEOF
 
 
 cat >>confdefs.h <<_ACEOF
@@ -24945,6 +25007,8 @@ cat >>confdefs.h <<_ACEOF
 #define BG_SERIAL "$bg_serial"
 _ACEOF
 
+ 		#define bluegene_loaded so we don't load another bluegene conf
+		bluegene_loaded=yes
    	fi
 
 
